# OpenAI 配置
openai:
  model: "gpt-4-turbo"
  temperature: 0.7
  max_tokens: 2000

# TradingView 配置
tradingview:
  base_url: "https://www.tradingview.com/chart"
  login_url: "https://www.tradingview.com/signin"
  default_timeframe: "1D"

# 策略評分權重
scoring:
  profit_factor: 0.3
  win_rate: 0.2
  sharpe_ratio: 0.2
  max_drawdown: 0.15
  trade_count: 0.15

# 強化學習參數
reinforcement:
  ppo:
    learning_rate: 0.0003
    n_steps: 2048
    batch_size: 64
  
  genetic:
    population_size: 50
    generations: 100
    mutation_rate: 0.1 